
favicon: /images/favicon.svg


menus:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Links: /links
  About: /about
  # More: /more
  # ......

social_contact:
  enable: false
  links:
    Email:
    Github: 
    WeChat:
    QQ:
    WeiBo:
    ZhiHu:
    Twitter:
    Facebook:
