
favicon: /images/favicon.svg


menus:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Links: /links
  About: /about
  # More: /more
  # ......

social_contact:
  enable: false
  links:
    Email:
    Github: 
    WeChat:
    QQ:
    WeiBo:
    ZhiHu:
    Twitter:
    Facebook:

comments:
  enable: true
  use: twikoo

  # Twikoo: A simple, safe, free comment system.
  # see: https://twikoo.js.org
  twikoo:
    version: 1.6.7  # Twikoo version, default use v1.6.7
    envId: https://twikoo-lihc.vercel.app/  # 腾讯云环境填 envId；Vercel 环境填地址 (https://xxx.vercel.app)
    region:         # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填

